### ISSUE TITLE
Cannot get root window (reopen, because previous was ignored)

### ISSUE THREAD

**Issue by handicraftsman** [PistonDevelopers/Piston-Tutorials#134]
Crashed with such error:
```bash
[ancient@NickolayPC piston_test]$ RUST_BACKTRACE=1 cargo run
     Running `target/debug/spinning-square`
thread '<main>' panicked at 'Failed to get root window: XError { description: "GLXBadFBConfig", error_code: 181, request_code: 156, minor_code: 34 }', ../src/libcore/result.rs:785
stack backtrace:
   1: 0x8029c8c4 - std::sys::backtrace::tracing::imp::write::h3800f45f421043b8
   2: 0x8029f8f1 - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
   3: 0x8029f531 - std::panicking::default_hook::hf3839060ccbb8764
   4: 0x80295a3a - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   5: 0x8029fbc3 - std::panicking::begin_panic::h9bf160aee246b9f6
   6: 0x802968bb - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
   7: 0x8029fb4b - rust_begin_unwind
   8: 0x802d6894 - core::panicking::panic_fmt::h93df64e7370b5253
   9: 0x801c3612 - core::result::unwrap_failed::h7a1dbd20d832f0c7
                at ../src/libcore/macros.rs:29
  10: 0x801c33e5 - _<std..result..Result<T, E>>::expect::h714ad72593951a33
                at ../src/libcore/result.rs:747
  11: 0x801ca2b3 - glutin::api::x11::window::Window::new::hd32d8ea8e3e76437
                at /home/ancient/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.6.1/src/api/x11/window.rs:423
  12: 0x801d83f5 - glutin::platform::platform::api_dispatch::Window::new::h2226469dadec9417
                at /home/ancient/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.6.1/src/platform/linux/api_dispatch.rs:197
  13: 0x801d97cc - glutin::window::_<impl WindowBuilder<'a>>::build::he61dd690f810f1a0
                at /home/ancient/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.6.1/src/window.rs:220
  14: 0x80111ca3 - glutin_window::GlutinWindow::new::hadb5f8ff401602df
                at /home/ancient/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-glutin_window-0.28.0/src/lib.rs:90
  15: 0x8016c730 - _<GlutinWindow as window..BuildFromWindowSettings>::build_from_window_settings::hf432412bd77e7da4
                at /home/ancient/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-glutin_window-0.28.0/src/lib.rs:284
  16: 0x80107ed0 - window::WindowSettings::build::h4b0739f263700f2b
                at /home/ancient/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-window-0.21.0/src/lib.rs:349
  17: 0x80101761 - spinning_square::main::h1452e5a9a43cce72
                at src/main.rs:53
  18: 0x8029f185 - std::panicking::try::call::hbbf4746cba890ca7
  19: 0x802a7e57 - __rust_try
  20: 0x802a7ded - __rust_maybe_catch_panic
  21: 0x8029ec1f - std::rt::lang_start::hbcefdc316c2fbd45
  22: 0x8010c6cd - main
  23: 0xb749a195 - __libc_start_main
  24: 0x800da1a0 - <unknown>
error: Process didn't exit successfully: `target/debug/spinning-square` (exit code: 101)
```
OS: GNU/Linux
Distro: ManjaroLinux (arch-based)
Arch: i686
Kernel version: 4.1
X.Org version: 1.17.4
Rust version: 1.10.0
Cargo version: 0.11.0-nightly
Source codes: You see... (really. Spinning-square tutorial)

**Comment by handicraftsman** [comment]
Lel. It's because of GL3_2. My GPU does not support it.
