### ISSUE TITLE
thread 'main' panicked at 'glx::MakeCurrent failed'

### ISSUE THREAD

**Issue by janhaa** [PistonDevelopers/Piston-Tutorials#144]
I get this backtrace when trying to run the getting-started example with RUST_BACKTRACE=1

```
$ RUST_BACKTRACE=1 cargo run
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/spinning-square`
thread 'main' panicked at 'glx::MakeCurrent failed', /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.1/src/api/glx/mod.rs:112
stack backtrace:
   1:     0x5599f57afcef - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:     0x5599f57b2f8d - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:     0x5599f57b2280 - std::panicking::default_hook::h0ac3811ec7cee78c
   4:     0x5599f57b2888 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:     0x5599f5670543 - std::panicking::begin_panic::h341b039f84d0b176
                        at /build/rust/src/rustc-1.13.0/src/libstd/panicking.rs:413
   6:     0x5599f5684d61 - <glutin::api::glx::Context as glutin::GlContext>::make_current::h26a6af546c73507a
                        at /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.1/src/api/glx/mod.rs:112
   7:     0x5599f564f2aa - <glutin::platform::platform::x11::Window as glutin::GlContext>::make_current::h593e5f65949413d9
                        at /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.1/src/platform/linux/x11.rs:224
   8:     0x5599f564f625 - <glutin::platform::platform::api_dispatch::Window as glutin::GlContext>::make_current::h86d04de3ec37a58f
                        at /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.1/src/platform/linux/api_dispatch.rs:214
   9:     0x5599f564dabb - glutin::window::<impl glutin::Window>::make_current::hca77c9fc2bc425cc
                        at /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.1/src/window.rs:431
  10:     0x5599f5650655 - glutin_window::GlutinWindow::new::h8b616a880ce2f506
                        at /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-glutin_window-0.33.0/src/lib.rs:101
  11:     0x5599f5652abb - <glutin_window::GlutinWindow as window::BuildFromWindowSettings>::build_from_window_settings::h76b4fb097e67814e
                        at /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-glutin_window-0.33.0/src/lib.rs:361
  12:     0x5599f560d0fb - window::WindowSettings::build::h50c02d80caa304a1
                        at /home/jan/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-window-0.24.0/src/lib.rs:367
  13:     0x5599f5614269 - spinning_square::main::h11d9fe1aa38a969d
                        at /home/jan/dev/piston/getting-started/src/main.rs:53
  14:     0x5599f57ba8e6 - __rust_maybe_catch_panic
  15:     0x5599f57b1af1 - std::rt::lang_start::h538f8960e7644c80
  16:     0x5599f5621ee3 - main
  17:     0x7f513d972290 - __libc_start_main
  18:     0x5599f5606299 - _start
  19:                0x0 - <unknown>```

**Comment by janhaa** [comment]
This seems to be related to this issue over at the glutin repository: [https://github.com/tomaka/glutin/issues/834](https://github.com/tomaka/glutin/issues/834)

**Comment by janhaa** [comment]
I was able to fix this by updating the dependencies in a fork of [https://github.com/PistonDevelopers/glutin_window/](https://github.com/PistonDevelopers/glutin_window/) to use the latest version from the [https://github.com/tomaka/glutin](https://github.com/tomaka/glutin) repository instead of the crates.io version.

So I guess one have to wait for the glutin guys to release a new version to crates and then update the dependency in [https://github.com/PistonDevelopers/glutin_window/](https://github.com/PistonDevelopers/glutin_window/) accordingly (or just always use the latest one?).

**Comment by vitvakatu** [comment]
@janhaa should we close this issue?
