### ISSUE TITLE
panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by despairblue** [PistonDevelopers/Piston-Tutorials#152]
```
    Finished debug [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/spinning-square`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
stack backtrace:
   1:     0x556b54b0c36a - std::sys::imp::backtrace::tracing::imp::write::ha21b0bc6fe1c6db2
   2:     0x556b54b0ec3f - std::panicking::default_hook::{{closure}}::h9e3ab7c535ab99bb
   3:     0x556b54b0e915 - std::panicking::default_hook::h8fcd4ede58ab2538
   4:     0x556b54b0f0d7 - std::panicking::rust_panic_with_hook::he3e7d4fe905c61c0
   5:     0x556b54b0ef64 - std::panicking::begin_panic::ha3d6117597a7c9fd
   6:     0x556b54b0ee89 - std::panicking::begin_panic_fmt::hf9da00dc881251f3
   7:     0x556b54b0ee17 - rust_begin_unwind
   8:     0x556b54b4e9bd - core::panicking::panic_fmt::hfe9893b7b5c72fdb
   9:     0x556b54b4e8f4 - core::panicking::panic::h4043ab79eb4deb98
  10:     0x556b549dc681 - <core::option::Option<T>>::unwrap::ha7d29db8d5055a9c
                        at /tmp/nix-build-rustc-1.15.drv-0/rust-10893a9/src/libcore/macros.rs:21
  11:     0x556b549f8cb9 - glutin::platform::platform::x11::Window::new::hdfa172117e791043
                        at /home/despairblue/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.4/src/platform/linux/x11.rs:117
  12:     0x556b549f6be7 - glutin::platform::platform::api_dispatch::Window::new::h44cb7e600d4b73da
                        at /home/despairblue/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.4/src/platform/linux/api_dispatch.rs:100
  13:     0x556b549fae4a - glutin::window::<impl glutin::WindowBuilder<'a>>::build::h2a743d786933a747
                        at /home/despairblue/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.7.4/src/window.rs:224
  14:     0x556b549cdf2d - glutin_window::GlutinWindow::new::h05277aa36f09e1b8
                        at /home/despairblue/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-glutin_window-0.35.0/src/lib.rs:89
  15:     0x556b549d0aeb - <glutin_window::GlutinWindow as window::BuildFromWindowSettings>::build_from_window_settings::h04ec181e8a9c3c9b
                        at /home/despairblue/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-glutin_window-0.35.0/src/lib.rs:318
  16:     0x556b5495825b - window::WindowSettings::build::h57520d747de9f6da
                        at /home/despairblue/.cargo/registry/src/github.com-1ecc6299db9ec823/pistoncore-window-0.26.2/src/lib.rs:387
  17:     0x556b5496ddda - spinning_square::main::hc22729755d8b6b70
                        at /home/despairblue/git/Piston-Tutorials/getting-started/src/main.rs:53
  18:     0x556b54b16d77 - __rust_maybe_catch_panic
  19:     0x556b54b112cd - std::rt::lang_start::hc9ebe7230cf52cfd
  20:     0x556b5496e2a2 - main
  21:     0x7f4c7332d2df - __libc_start_main
  22:     0x556b5494f999 - _start
                        at ../sysdeps/x86_64/start.S:120
  23:                0x0 - <unknown>
```

I'm probably missing some so files. Don't know which though.

**Comment by vitvakatu** [comment]
Seems like similar problem as in #153
