### ISSUE TITLE
Can not build examples.  libloading 0.5.0 failing.

### ISSUE THREAD

**Issue by tm-nihonsuki** [PistonDevelopers/Piston-Tutorials#209]
Can not compile any examples.  I'm new to Rust and may have misunderstood some aspect of installation.  Running nightly toolchain on Nixos.  All parts but libloading compiling fine.  

Example below:

```
extern crate piston_window;

use piston_window::*;

fn main() {
    let mut window: PistonWindow = 
        WindowSettings::new("Hello Piston!", [640, 480])
        .exit_on_esc(true).build().unwrap();
    while let Some(e) = window.next() {
        window.draw_2d(&e, |c, g| {
            clear([1.0; 4], g);
            rectangle([1.0, 0.0, 0.0, 1.0], // red
                      [0.0, 0.0, 100.0, 100.0],
                      c.transform, g);
        });
    }
}

```

Output below:

```
   Compiling libloading v0.5.0
error: failed to run custom build command for `libloading v0.5.0`
process didn't exit successfully: `/home/tony/workspace/rust/Piston42/target/debug/build/libloading-691a31060dac4662/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=dl
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-o" "/home/tony/workspace/rust/Piston42/target/debug/build/libloading-ef198268ca66ed9e/out/src/os/unix/global_static.o" "-c" "src/os/unix/global_static.c"
exit code: 0
AR_x86_64-unknown-linux-gnu = None
AR_x86_64_unknown_linux_gnu = None
HOST_AR = None
AR = None
running: "ar" "crs" "/home/tony/workspace/rust/Piston42/target/debug/build/libloading-ef198268ca66ed9e/out/libglobal_static.a" "/home/tony/workspace/rust/Piston42/target/debug/build/libloading-ef198268ca66ed9e/out/src/os/unix/global_static.o"

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "ar" "crs" "/home/tony/workspace/rust/Piston42/target/debug/build/libloading-ef198268ca66ed9e/out/libglobal_static.a" "/home/tony/workspace/rust/Piston42/target/debug/build/libloading-ef198268ca66ed9e/out/src/os/unix/global_static.o" with args "ar" failed to start.

', /home/tony/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.29/src/lib.rs:2314:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:340
   7: cc::fail
             at /home/tony/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.29/src/lib.rs:2314
   8: cc::Build::compile
             at /home/tony/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.29/src/lib.rs:951
   9: build_script_build::main
             at ./build.rs:27
  10: std::rt::lang_start::{{closure}}
             at /rustc/b244f61b77c42d7be695afd7901ee4418559e518/src/libstd/rt.rs:64
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:90
  13: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  14: std::rt::lang_start
             at /rustc/b244f61b77c42d7be695afd7901ee4418559e518/src/libstd/rt.rs:64
  15: main
  16: __libc_start_main
  17: _start
             at ../sysdeps/x86_64/start.S:120
```

**Comment by tm-nihonsuki** [comment]
Problem seems to be that binutils was not brought in as a dependency by any other package and had to be installed explicitly.
